### ISSUE TITLE
lsusb for windows

### ISSUE THREAD

**Issue by Roman-Koshelev** [gregkh/usbutils#102]
Why not lsusb under windows? You can collect it with minimal edits ...

**Comment by gregkh** [comment]
I can collect what with minimal edits?

This is a tool for Linux and libusb-based systems.  If you have patches to get it to work on Windows, by all means submit them here, otherwise this is not a real "issue" for me.

**Comment by Roman-Koshelev** [comment]
libusb works on windows too. I ran lsusb under windows and linux. You can see the difference yourself (there is almost none). [https://yadi.sk/d/ouWXtDHKgwlBwA](url)

**Comment by ValZapod** [comment]
But you will need an instruction how to compile with Visual Studio 2019, also please instead of Yandex, attach it here on github (drag and drop zif file)! This is cool, like I did to edid-decode library.
