### ISSUE TITLE
When is next release/tag planned?

### ISSUE THREAD

**Issue by grundlerchromium** [gregkh/usbutils#132]
vapier@chromium.org and I are wondering if there is a plan for the next release.

It appears the most recent release was Oct 2020 (V013) and the repo has nearly 30 changes since then:
grundler <2241>git log --oneline v013.. | fgrep -v "Merge pull request" | wc -l
29

thanks,
grant

**Comment by gregkh** [comment]
I can do a release soon.  Let me make sure all pending work is caught up on, normally I do one release a year or so for this slow-moving codebase :)

**Comment by grundlerchromium** [comment]
Ok - thanks - no stress to release though. Not looking for a regular candence - just understand roughly when you feel ready to "ship" the next release.

**Comment by gregkh** [comment]
Usually when someone asks me because a feature was added that they need.  No regular cadence at all here.

**Comment by gregkh** [comment]
A release happened since then, closing this out.
