### ISSUE TITLE
broken email for lsusb AUTHOR Thomas Sailer in man page

### ISSUE THREAD

**Issue by idallen** [gregkh/usbutils#145]
~~~~~
<sailer@ife.ee.ethz.ch>: host mc4.ethz.ch[82.130.86.12] said: 550-Callout
    verification failed: 550-550 5.1.10 RESOLVER.ADR.RecipientNotFound;
    Recipient not found by SMTP 550 address lookup (in reply to RCPT TO
    command)
~~~~~

**Comment by gregkh** [comment]
Do you have an updated email address?  If not, might as well just leave it as-is.

**Comment by idallen** [comment]
Sorry, I should have mentioned that I tried to find an update address and failed.
You will save others time if you remove the invalid email address so that we all don't waste time trying it
(and then don't waste time reporting to you that the email is broken).
