### ISSUE TITLE
lsusb names are mixed

### ISSUE THREAD

**Issue by Lowrida** [gregkh/usbutils#146]
I had a video capture device without a name and a problem of mixed up names of my keyboard with webcam and phone..
 
![lsusb1](https://user-images.githubusercontent.com/53632533/169103809-92edc461-7480-4c62-9ddf-7a7526d43dfd.jpg)

So i installed **20-usb-vendor-model.hwdb** to **/etc/udev/hwdb.d** and updated the database. Now my video capture device has a name, but the mixing of names from my keyboard (green) and the creative webcam (red) is still an issue. The mixing of names with keyboard an my Huawei P10 is gone now!
 
![lsusb2](https://user-images.githubusercontent.com/53632533/169104179-85e46b3c-e73c-4cb4-b4b5-12e38963f284.jpg)
 
Any idea what this could be? Something wrong on my system or a bug??
I am on Linux Mint 20.3 with kernel 5.14 and lsusb version 012.

**Comment by gregkh** [comment]
lsusb 012 is from 2019, this issue should already be fixed, please update to 014 and see if it is still there or not.

If it is an issue with 014, please reopen, thanks!

**Comment by Lowrida** [comment]
014 solved the problem! Thanks.
