### ISSUE TITLE
lsusb installed from brew (brew install usbutils) on MacOS gives no output.

### ISSUE THREAD

**Issue by biGdada** [gregkh/usbutils#147]
when i run lsusb without parameters i get no output.

> biGdada@biGdadas-MacBook-Pro ~ % lsusb -V
> lsusb (usbutils) 014
> biGdada@biGdadas-MacBook-Pro ~ % lsusb 
> biGdada@biGdadas-MacBook-Pro ~ % lsusb -t
> lsusb -t is only supported on Linux

Monterey, MacBook Pro 2018.

**Comment by alfwatt** [comment]
`brew remove lsusb`

`brew install usbutil`
