### ISSUE TITLE
USB MIDI 2.0 Descriptors

### ISSUE THREAD

**Issue by symdeb** [gregkh/usbutils#154]
This is output from lsusb on Ubuntu 22.04.01. This is a prototype MIDI 2.0  (UMP)  USB device using alternate setting 1 descriptors
Descriptor type 37 subtype 2 is supposed to list bNumGrpTrmBlock but it shows  MIDIJack.
Reference: USB Device Class Definition for MIDI Devices, Version 2.0 p.42.
Not sure where to post this. Only could find this github repo with libusb sources
Have no reference to other devices as a comparison (no such devices seem to exist yet).

**Comment by symdeb** [comment]
[MIDI_2_Alt_setting_1.txt](https://github.com/gregkh/usbutils/files/9422500/MIDI_2_Alt_setting_1.txt)

**Comment by gregkh** [comment]
This is the correct repo, yes.

I don't understand the problem here, what does the output show and what should it show exactly?

**Comment by symdeb** [comment]
This is what the tool reports:

        MIDIStreaming Endpoint Descriptor:
          bLength                 5
          bDescriptorType        37
          bDescriptorSubtype      2 (Invalid)
          bNumEmbMIDIJack         1
          baAssocJackID( 0)       1

![Screenshot from 2022-08-25 19-54-36](https://user-images.githubusercontent.com/19564066/186657647-473c9f08-d2e9-4c03-87de-049c090f2910.png)

**Comment by gregkh** [comment]
Thanks for the info, should now be fixed in the tree in commit f7cb6bcf153d ("lsusb: fix up Midi Device specification devices")

Can you pull the latest tree and build and test it to verify?

**Comment by symdeb** [comment]
git checkout f7cb6bc
HEAD is now at f7cb6bc lsusb: fix up Midi Device specification devices
Ther error is gone but the field names are not updated :  bNumEmbMIDIJack ,  baAssocJackID( 0)

**Comment by symdeb** [comment]
Posted a pull request for this.
