### ISSUE TITLE
Strange usb request to device

### ISSUE THREAD

**Issue by alexeyk13** [gregkh/usbutils#28]
Hello!

I'm embedded developer and got some strange USB request from lsusb.

lsusb -d 24dc:0401 -v

Unhandled STANDART request
bmRequestType: 80
bRequest: 6
wValue: A00
wIndex: 0
wLength: 4

What is 0xA descriptor type? I don't found it in USB2.0 specification.

**Comment by gregkh** [comment]
Look in the USB 3 specification, it should be in there somewhere...

**Comment by gregkh** [comment]
If not, please bring this up on the linux-usb@vger.kernel.org mailing list, and the developers can help you out.
