### ISSUE TITLE
Package description vs. version 008

### ISSUE THREAD

**Issue by n0-1** [gregkh/usbutils#29]
Description says:

> USB utilities for Linux, includes the usb.ids file and lsusb http://www.linux-usb.org

But 5d7ea40bc94cbf3069a25beba3146de13bcdcf02 tells otherwise:

> Also remove usb.ids from the repository. [Note that these were probably
> never used by distributions regarless, as most distros ship the usb.ids
> directly from upstream.]

**Comment by gregkh** [comment]
Thanks for pointing it out, now fixed.
