### ISSUE TITLE
Please consider adding a utility to reset USB devices

### ISSUE THREAD

**Issue by Zugschlus** [gregkh/usbutils#34]
Hi,

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=554122 has a bunch of links to various utilities that can be used to issue a (soft) reset to certain USB devices. This might be helpful in situations where a device is remote so that pulling and re-plugging the device is not an option.

It would be great if such an utility could be included in a future version of usbutils.

Thanks in advance!

Greetings
Marc

**Comment by gregkh** [comment]
On Sun, Sep 06, 2015 at 01:51:18AM -0700, Zugschlus wrote:
> Hi,
> 
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=554122 has a bunch of links
> to various utilities that can be used to issue a (soft) reset to certain USB
> devices. This might be helpful in situations where a device is remote so that
> pulling and re-plugging the device is not an option.
> 
> It would be great if such an utility could be included in a future version of
> usbutils.

The utility does not work on the majority of systems out there as this
is not a mandated feature for USB hubs, so almost no one implements it.
I don't want to add a tool to the repo that doesn't work for anyone,
and have to deal with the support nightmare of having to explain it all
of the time.

sorry,

greg k-h
