### ISSUE TITLE
Endianness of guids

### ISSUE THREAD

**Issue by tsundre** [gregkh/usbutils#42]
lsusb prints guids in the transmitted byte order. Since there is a comment about byte order in the get_guid function that refers to RFC 4122, I assume this is not by coincidence.  However, at least for UVC, this results in guids being printed differently from the ones listed in the documentation. 

As an example, according to the specification for UVC1.1 Uncompressed Payload, the following GUID is supposed to represent YUY2:
{32595559-0000-0010-8000-00AA00389B71}
In the lsusb output, this is printed as:
{59555932-0000-1000-8000-00aa00389b71}

According to RFC 4122, the three first fields are supposed to be big-endian. According to chapter 8.1 in the USB 2.0 specification, USB trasmission order is little-endian.

To me, it looks like it would be correct to swap byte order for the first three fields when printing.

**Comment by gregkh** [comment]
Thanks for your patch, now merged.
