### ISSUE TITLE
lsusb with -v flag hangs for a few seconds

### ISSUE THREAD

**Issue by xosevp** [gregkh/usbutils#50]
See the transition from 02:25:29 to 02:25:34 in the log: [lsusb-v.txt](https://github.com/gregkh/usbutils/files/736608/lsusb-v.txt) (strace -o lsusb-v.txt -f -t lsusb -v)

[...]
6156  02:25:29 timerfd_settime(9, TFD_TIMER_ABSTIME, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=14426, tv_nsec=79963000}}, NULL) = 0
6156  02:25:29 ioctl(10, USBDEVFS_SUBMITURB, 0x55ec1208f170) = 0
6156  02:25:29 poll([{fd=7, events=POLLIN}, {fd=9, events=POLLIN}, {fd=10, events=POLLOUT}], 3, 60000) = 1 ([{fd=9, revents=POLLIN}])
6156  02:25:34 ioctl(10, USBDEVFS_DISCARDURB, 0x55ec1208f170) = 0
[...]

Thanks.

**Comment by gregkh** [comment]
Devices can be slow to respond at times, not much we can do about that in userspace.

Closing this out now.
