### ISSUE TITLE
Next release for usbutils?

### ISSUE THREAD

**Issue by S4mw1s3** [gregkh/usbutils#57]
Is it possible to make a new release of usbutils? The last release was v008 on Oct 21, 2014 and I need some fixes from usbhid-dump. The usbhid-dump submodule already points to the most recent commit, but since no new release of usbutils is made since 2014, my distro doesn't contain the fixes I'm interested yet...

**Comment by timofonic** [comment]
@S4mw1s3 I agree. I like the "release early, release often" phrase. usbutils are an important part of utilities that deserve more love (and developers). 009 appeared and that's good, but I hope it happens more often

@gregkh What do you think?

**Comment by gregkh** [comment]
009 is now released, sorry for the delay.
