### ISSUE TITLE
Suggestion: update-usbiids, a command to update usb db like pciutils' update-pciids. Send unknown USB IDs

### ISSUE THREAD

**Issue by timofonic** [gregkh/usbutils#58]
Hello.

What about this?

I commonly find devices that my system is unable to identify properly.

Any way to automatically send unknown USB devices somewhere too?

Kind regards

**Comment by gregkh** [comment]
There is no usb.ids file as part of usbutils anymore, sorry.  So there's not much we can do here.  And it turns out that keeping this kind of list doesn't really mean anything, which is why it was removed, as it is not needed.
