### ISSUE TITLE
Release 009 not on kernel.org

### ISSUE THREAD

**Issue by rworkman** [gregkh/usbutils#59]
Please upload 009 to http://www.kernel.org/pub/linux/utils/usb/usbutils/ 

Alternatively, make a note in that directory that github is the canonical source now.

**Comment by rworkman** [comment]
Also, the tarball downloaded from github doesn't have a configure script, and autogen.sh won't run as-is since the directory doesn't have the git structure.

**Comment by gregkh** [comment]
The release is now on kernel.org, sorry for the delay, took a while to get the scripts all working to push it there.

And no, github is not the "canonical" source, just one of the many places it is hosted at...
