### ISSUE TITLE
Make it clear the tool is not relying on the usb.ids file anymore

### ISSUE THREAD

**Issue by notorand-it** [gregkh/usbutils#62]
It looks like (strace) the tool is not using the usb.ids text file any more.
The manual page says otherwise.

**Comment by gregkh** [comment]
The lsusb.py tool in the repo still does use the usb.ids file.  So keeping it here is a nice idea for now.

thanks for the report!

**Comment by notorand-it** [comment]
Nonetheless I'd update the **manual page** to reflect the actual behavior.
I'm saying you'd just make clear to users that the usb.ids file is not being used by lsusb but it's being used by lsusb.py. If I update that file, lsusb won't show any new detail, while lsusb.py will.
