### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by lnykryn** [gregkh/usbutils#65]
Would it be possible to do a new release in the near future? I am preparing the package for a new major version of a distribution and I would rather use a official release then a git snapshot. Thanks!

**Comment by gregkh** [comment]
Good idea, let me go work on that and make sure I've caught up on all pending patches...

**Comment by lnykryn** [comment]
Great! Thanks.

**Comment by gregkh** [comment]
010 release is now done, tagged, and tarballs are on kernel.org if you want to use them.
