### ISSUE TITLE
lsusb stalls with "UNRECOGNIZED" errors

### ISSUE THREAD

**Issue by h1z1** [gregkh/usbutils#66]
Not sure if this is a problem upstream or with lsusb.   Can confirm at least with the latest git (010) and CentOS release (007).

007:  Strange thing is it also appears on virtual hubs:
https://gist.github.com/h1z1/d21035ec804de5ad77f9487479e039a4
```
    bU2DevExitLat           0 micro seconds
  **** UNRECOGNIZED:  1c 10 0a 00 23 00 00 00 01 00 00 00 34 00 05 00 b4 00 05 00 35 40 0a 00 b5 40 0a 00**
Device Status:     0x0001
  Self Powered
```

010:  Different error possibly related?
https://gist.github.com/h1z1/d21035ec804de5ad77f9487479e039a4
```
      Speed Attribute ID: 5 10Gb/s Symmetric TX SuperSpeedPlus
**can't get debug descriptor: Resource temporarily unavailable**
Device Status:     0x0001
  Self Powered
```

**Comment by gregkh** [comment]
Looks like an upstream kernel issue, please send this to the linux-usb@vger.kernel.org mailing list.  But first make sure you are using the latest kernel version, I have no idea what ancient kernel centos is using, odds are that might be your problem right there, sorry.

**Comment by h1z1** [comment]
Ah.   For posterity, the kernel above is  4.16.1-1.el7.elrepo.x86_64  (aka kernel-ml)
