### ISSUE TITLE
lsusb.py not fully converted to Python 3

### ISSUE THREAD

**Issue by birkenfeld** [gregkh/usbutils#68]
The conversion (from commit f5238739b42841d6e9cfd0e812adbf59a73c08b7) seems incomplete. usb.ids cannot be read because `file()` does not exist anymore in Py3.

Replacing this with `open()`, a decode error occurs because the usb.ids file is inconsistently encoded, or at least not UTF-8.

/cc @lnykryn

**Comment by gregkh** [comment]
Ah, odd that it doesn't throw an error, you would think that it would be smarter than that :)

Care to make up a patch and submit it?

**Comment by gregkh** [comment]
oh wait, if the file is not correctly encoded, we can get that fixed up in that package, but it is not packged in usbutils anymore.  So we need to be able to parse it properly, or probably best yet, just don't even care about it at all.

**Comment by birkenfeld** [comment]
Ok - the PR will ignore UTF-8 encoding errors. The only problem I found when taking a closer look is this line from the "List of HID usages" under "HUT 07 Keyboard":
```
        034  ´ and " (Accent Acute and Double Quotes)
```
where the acute accent is in Latin-1 instead of UTF-8.

Where would be the right place to fixup usb.ids?

**Comment by garloff** [comment]
I have added errors='ignore' into the lsusb.py code. So we don't fail the reading b/c of one bad entry...
Will create a PR to merge back my changes (there are more...) soon.
