### ISSUE TITLE
DNS Queries to get updated ID information

### ISSUE THREAD

**Issue by DeftNerd** [gregkh/usbutils#72]
I noticed today that even though I'm running Ubuntu 18.04, my usb ID database was from 2017. 

The pci-id database operates at `pci-ids.ucw.cz`, and the lspci command has a neat feature. 

When pci-ids.ucw.cz updates their database, they generate and apply a DNS zone file and create TXT records for the ID records. 

If you have a PCI ID of `0014:7a00`, you can do a DNS TXT query for `0014.pci-ids.ucw.cz` and the record is `i=Loongson Technology LLC` showing the manufacturer. If you `dig txt 7a00.0014.pci.id.ucw.cz" you get `i=Hyper Transport Bridge Controller`

It's an easy way to update the local database for specific entries without having to sync the entire pci.ids file. lspci has native support for the DNS search method so there are never any unrecognized devices.

I think lsusb and the usb.ids file could benefit from a similar configuration. [Michal 'vorner' Vaner](http://vorner.cz/en/index.html#contact) could likely assist with the code merges from lspci to lsusb as well as help you work out the DNS infrastructure (or if you ask nicely, he might just let you use his DNS servers to host the linux-usb.org zone DNS information)

**Comment by gregkh** [comment]
The usb.ids file is not shipped as part of this package anymore (and has not for quite some time.)  So there's nothing I can do here.  It comes as part of the hwids package for your distro, please work with that community.

Also, you would need to work with the usb.ids provider to provide support over DNS, which is outside of this project's scope.

Sorry.
