### ISSUE TITLE
Insufficient minimum version for libusb

### ISSUE THREAD

**Issue by ebassi** [gregkh/usbutils#83]
Commit 89a279cd2acae0aa8b6126af3dc417c4ecd89fe6 updated the version of usbhid-dump to the latest commit, but usbhid-dump now requires libusb ≥ 1.0.22, as it uses `libusb_set_options()` — see DIGImend/usbhid-dump#4 for the missing version check there.

Usbutils depends on libusb ≥ 1.0.9, but since it builds usbhid-dump as a sub-module, it should bump up the required version of libusb to 1.0.22.

**Comment by gregkh** [comment]
sounds good, care to provide a patch for this?
