### ISSUE TITLE
Update man for -t "This overrides the v option." after commit b4c4da2

### ISSUE THREAD

**Issue by ValZapod** [gregkh/usbutils#85]
I suppose now -t option does not override -v option as you can increase verbosity for -t after b4c4da2.

Also I have a question about debian repository https://packages.debian.org/search?keywords=usbutils&searchon=names&suite=all&section=all
As you can see only experemental has 010 version, while all other have 007 version which does not have this commit f10dd91, so there are problems with MaxPower. Maybe it is possible to add a patch to https://sources.debian.org/patches/usbutils/1:007-4/ or better move 010 version to stable?

**Comment by gregkh** [comment]
Note, I have no control over any debian anything.  If you have a question/issue with how usbutils is packaged there, please contact the distro and the packagers there.

As for the -v option, good catch, can you make a patch for the man page for this change?
