### ISSUE TITLE
Please do a release with Python 3 support

### ISSUE THREAD

**Issue by nanonyme** [gregkh/usbutils#91]
v010 doesn't support Python 3 and Python 2 is being EOL'd in 2020 and it's gradually disappearing from default configurations for distros. Apparently the support is added in trunk. Is there any chance of having a new release soon?

**Comment by gregkh** [comment]
Not a bad idea, a number of small changes have happened since the last release, might as well cut one in a few days, thanks!

**Comment by gregkh** [comment]
011 and really, the 012 release now should resolve this issue.

If not, please let me know!
