### ISSUE TITLE
The null pointer is passed into 'free' function

### ISSUE THREAD

**Issue by ValZapod** [gregkh/usbutils#96]
I suppose there is a mistake
https://github.com/gregkh/usbutils/blob/467546cffeae9d2f94414b00871f821010a19f28/lsusb.c#L1345
because *name is not used at all.

Also there is some other typos auto analyses tool found.

/opt/SourceCode/usbutils/desc-defs.c    970     warn    V557 Array overrun is possible. The value of 'value' index could reach 6.
/opt/SourceCode/usbutils/lsusb.c        1344    err     V575 The null pointer is passed into 'free' function. Inspect the first argument.
/opt/SourceCode/usbutils/lsusb.c        1447    err     V629 Consider inspecting the 'buf[j + 9 + buf[4] * 2] << (8 * j)' expression. Bit shifting of the 32-bit value with a subsequent expansion to the 64-bit type.
/opt/SourceCode/usbutils/lsusb.c        3393    warn    V576 Incorrect format. Consider checking the sixth actual argument of the 'printf' function. Under certain conditions the pointer can be null.
/opt/SourceCode/usbutils/usbreset.c     169     warn    V576 Incorrect format. Consider checking the third actual argument of the 'sscanf' function. A pointer to the unsigned int type is expected.
/opt/SourceCode/usbutils/usbreset.c     169     warn    V576 Incorrect format. Consider checking the fourth actual argument of the 'sscanf' function. A pointer to the unsigned int type is expected.
/opt/SourceCode/usbutils/names.c        442     warn    V519 The 'r' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 438, 442.

**Comment by gregkh** [comment]
*name is now removed, thanks!

Will look at the others, but the best way to resolve these are if you submit patches :)
