### ISSUE TITLE
Cannot mount USB floppy disk drive

### ISSUE THREAD

**Issue by jowyta** [gregkh/usbutils#99]
Device is recognised as a floppy when it is plugged in and allocated to /dev/sdb if plugged in after the system has booted.   A device /dev/sg1 is also created.  ufiformat -v -i gives the same output for sdb and sg1.
Kernel is 5.2.17 compiled from Debian source.  CONFIG_USB_STORAGE=y
Drive is identified as 0409:0040 NEC Corp. Floppy
~# mount /dev/sdb /media/floppy
mount: /media/floppy0: can't read superblock on /dev/sdb.
~# mount /dev/sg1 /media/floppy
mount: /media/floppy0: /dev/sg1 is not a block device.

~# mount -t msdos /dev/sdb /media/floppy
mount: /media/floppy0: can't read superblock on /dev/sdb.
from dmesg:
[47430.337431] sd 2:0:0:0: [sdb] tag#0 access beyond end of device
[47430.337444] print_req_error: I/O error, dev sdb, sector 0 flags 0
[47430.337458] FAT-fs (sdb): unable to read boot sector

**Comment by gregkh** [comment]
usbutils is not in charge of mount/unmount any devices, that is the normal 'mount' command on Linux.

This looks like you just have a problem with your disk device, please ask for support from your Linux distro for this, nothing I can do here, sorry.
